### ISSUE TITLE
Couldn't you change the library name in the .config files dllmap instead?

### ISSUE THREAD

**Issue by schlenk** [cuga-rajal/opensim_apple_arm64#1]
I wondered if you could change the libopenjpeg library filenames in the config files for opensim instead of renaming it to bogus x86_64 names?

See:

-  http://opensimulator.org/viewgit/?a=viewblob&p=opensim&h=a06109b49c4cd5f806cdf549acda26a932b1418e&hb=9d9a6f0fe8d93ae45b2b1fb31a3f7a35d8895157&f=bin/OpenMetaverse.dll.config

- http://opensimulator.org/viewgit/?a=viewblob&p=opensim&h=be047c23398c11b6c472b567d869521f66e03dac&hb=9d9a6f0fe8d93ae45b2b1fb31a3f7a35d8895157&f=bin/OpenSim.Region.PhysicsModule.BulletS.dll.config

**Comment by cuga-rajal** [comment]
According to Ubit, this renaming with bogus architecture in the filename is the only way to get it to load in dotnet. The .config files are only used with mono. Ubit is correct, if I try any other file naming the file is not found. I agree this is not good, but it is the only way that works currently.

**Comment by cuga-rajal** [comment]
I did try adding entires in the config and they are ignored. Ubit says those are only used with mono.

**Comment by cuga-rajal** [comment]
Config files for loading obODE and Bullet libraries are also ignored by dotnet6. The Bullet and obODE dylibs also have reserved names and have to overwrite files provided in trunk, for the same reason.

**Comment by cuga-rajal** [comment]
If this situation changes in the future and the config files are used in dotnet, the correct thing is to name these with the arm64 architecture and place them in /bin/lib64.
